# Generated by Django 4.0.5 on 2023-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Weight', models.FloatField(db_index=True, max_length=10)),
                ('Item_MRP', models.FloatField(db_index=True, max_length=10)),
                ('Item_Visibility', models.FloatField(max_length=10)),
                ('Item_Fat_Content', models.CharField(max_length=10)),
                ('Outlet_Type', models.CharField(max_length=10)),
                ('item_type', models.CharField(max_length=10)),
                ('Outlet_Size', models.CharField(max_length=10)),
            ],
        ),
    ]
