# Generated by Django 4.0.5 on 2023-04-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Item_MRP',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Item_Weight',
            field=models.FloatField(max_length=10),
        ),
    ]
